syntax = "proto3";
package user;
option go_package = "github.com/stokth/Gorilla/project-protos/proto/user";

// Сущность пользователь (минимум полей)
message User {
  int64 id    = 1;
  string email = 2;
}

message Task {
  int64 id      = 1;
  string task   = 2;
}

// Запрос на создание
message CreateUserRequest {
  string email = 1;
}
message CreateUserResponse {
  User user = 1;
}

// Запрос на получени определенного User
message GetUserRequest {
    int64 id = 1;
}
message GetUserResponse {
    User user = 1;
}

// Запрос на получение всех Users
message GetUsersRequest {
}
message GetUsersResponse {
    repeated User users = 1;
}

// Обновить юзера
message UpdateUserRequest {
    int64 id = 1;
    string email = 2;
}
message UpdateUserResponse {
    User user = 1;
}

//Удалить юзера
message DeleteUserRequest {
    int64 id = 1;
}
message DeleteUserResponse {
}

// Получить все таски опред. юзера
message GetTaskForUserRequest {
    int64 id = 1;
}
message GetTaskForUserResponse {
    repeated Task tasks = 1;
}

service UserService {
  rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
  rpc GetUser    (GetUserRequest)              returns (GetUserResponse);
  rpc GetUsers   (GetUsersRequest) returns (GetUsersResponse);
  rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
  rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
  rpc GetTasksForUser (GetTaskForUserRequest) returns (GetTaskForUserResponse);
}