syntax = "proto3";
package task;
option go_package = "github.com/stokth/Gorilla/project-protos/proto/task";

// Сущность задача
message Task {
  int64 id      = 1;
  string task   = 2;
}

// Запрос на создание задачи
message CreateTaskRequest {
  string task = 1;
}
message CreateTaskResponse {
  Task task = 1;
}

// Запрос на получение задачи
message GetTaskRequest {
    int64 id = 1;
}
message GetTaskResponse {
    Task task = 1;
}

// Запрос на получение всех задач
message GetTasksRequest {

}
message GetTasksResponse {
    repeated Task tasks = 1;
}

// Запрос на обновление задачи
message UpdateTaskRequest {
    int64 id = 1;
    string task = 2;
}
message UpdateTaskResponse {
    Task task = 1;
}

// Запрос на удаление задачи
message DeleteTaskRequest {
    int64 id = 1;
}
message DeleteTaskResponse {

}

service TaskService {
  rpc CreateTask (CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTask    (GetTaskRequest)             returns (GetTaskResponse);
  rpc GetTasks (GetTasksRequest) returns (GetTasksResponse);
  rpc UpdateTask (UpdateTaskRequest) returns (UpdateTaskResponse);
  rpc DeleteTask (DeleteTaskRequest) returns (DeleteTaskResponse);
} 